name: Builds
on: [push]
jobs:
  linux-opt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: ldc-latest
      - run: make -C minivm CC=cc OPT='-Os'
      - run: make DC=ldc2
      - run: cp minivm/bin/* bin/
      - uses: actions/upload-artifact@v2
        with:
          name: minivm-linux
          path: |
            bin/*
          if-no-files-found: error