name: Builds
on: [push]

env:
  EM_VERSION: 1.39.18
  EM_CACHE_FOLDER: 'emsdk-cache'

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: ldc-latest
      - run: make -C minivm CC=cc OPT='-Os'
      - run: make DC=ldc2
      - run: cp minivm/bin/{minivm,minivm-color,minivm-dis} bin/
      - uses: actions/upload-artifact@v2
        with:
          name: dbrew-linux
          path: |
            bin/*
          if-no-files-found: error
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: ldc-latest
      - run: make -C minivm CC=cc OPT='-Os'
      - run: make DC=ldc2
      - run: cp minivm/bin/{minivm,minivm-color,minivm-dis} bin/
      - uses: actions/upload-artifact@v2
        with:
          name: dbrew-mac
          path: |
            bin/*
          if-no-files-found: error
  wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: ldc-latest
      - name: Setup cache
        id: cache-system-libraries
        uses: actions/cache@v2
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{ runner.os }}
      - uses: mymindstorm/setup-emsdk@v11
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
      - run: make -C minivm CC=cc OPT='-Os'
      - run: env ./wasm.sh
      - uses: actions/upload-artifact@v2
        with:
          name: dbrew-wasm
          path: |
            bin/dbrew.wasm
          if-no-files-found: error
    windows:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2
          with:
            submodules: true
        - uses: dlang-community/setup-dlang@v1
          with:
            compiler: ldc-latest
        - uses: egor-tensin/setup-mingw@v2
          with:
            platform: x64
        - run: cd minivm && make CC=cc OPT='-Os'
        - run: make DC=ldc2 CC=cc OPT='-Os'
        - uses: actions/upload-artifact@v2
          with:
            name: minivm-windows.exe
            path:  | 
              bin/dbrew.wasm